# Use new Travis-CI container Infrastructure for faster builds
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - nightly
    - php: hhvm-nightly # LTS version of HHVM (change when latest is no longer LTS)
      sudo: true # Travis-CI container Infrastructure doesn't support all available HHVM versions, so use Trusty
      dist: trusty
      group: edge # Until the next update
      addons:
        apt:
          packages:
            - libxml2-utils
      env: HHVMPHP7="no"
    - php: hhvm-nightly # LTS version of HHVM with PHP7 mode (change when latest is no longer LTS)
      sudo: true # Travis-CI container Infrastructure doesn't support all available HHVM versions, so use Trusty
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - libxml2-utils
      env: HHVMPHP7="yes"
    - php: hhvm # Current version of HHVM (could be LTS or STS)
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - libxml2-utils
      env: HHVMPHP7="no"
    - php: hhvm # Current version of HHVM with PHP7 mode (could be LTS or STS)
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - libxml2-utils
      env: HHVMPHP7="yes"
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm-nightly
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo 'xdebug.enable = 1' >> /etc/hhvm/php.ini; fi # Extension xdebug is required

script:
  - ./phpunit --debug --verbose --filter 'dependencies3-isolation'
  - ./phpunit --configuration --debug --verbose --filter 'dependencies3-isolation' ./build/travis-ci-fail.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  - xmllint --noout --schema phpunit.xsd phpunit.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_empty.xml
  - xmllint --noout --schema phpunit.xsd tests/_files/configuration_xinclude.xml -xinclude
  
notifications:
  email: false
